version: "3"
services:
  api:
    image: $REGISTRY/chrisdavis03/${PACKAGE_REPO}/${IMAGE_NAME_API}:${VERSION}
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    ports:
      - "8000:8000"
    command: "/start"
