[tool.semantic_release]
branch = "main"
upload_to_pypi = false
upload_to_repository = false
upload_to_release = false
version_source = "tag"
commit_version_number = true
commit_message = "chore(release): v{version} [skip ci]"
