name: build-publish
on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      version:
        required: true
        type: string
      image-name-api:
        required: true
        type: string

jobs:
  build:
    name: Build & push docker image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build with compose
        env:
          REGISTRY: ${{ inputs.registry }}
          IMAGE_NAME_API: ${{ inputs.image-name-api }}
          VERSION: ${{ inputs.version }}
          PACKAGE_REPO: ${{ github.repository }}
        run: docker compose build

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_REPO_TOKEN }}

      - name: publish to GHCR
        run: docker push ${{ inputs.registry }}/chrisdavis03/${{ github.repository }}/${{ inputs.image-name-api }}:${{ inputs.version }}
