name: nightly-build
on:
  schedule:
    # hourly.
    - cron: "*/15 * * * *"

jobs:
  call-check-should-run:
    uses: ./.github/workflows/should_run.yml
    with:
      foo: "whiz"

  echo_should_run:
    runs-on: ubuntu-latest
    needs: call-check-should-run
    steps:
      - name: print output
        env:
          SHOULD_RUN: ${{ needs.call-check-should-run.outputs.should_run }}
        run: echo "$SHOULD_RUN"

  build_condintional:
    runs-on: ubuntu-latest
    needs: call-check-should-run
    steps:
      - name: nightly build
        if: ${{ needs.call-check-should-run.outputs.should_run }} == true
        run: echo "run nightly build"

  call-notify-slack:
    uses: ./.github/workflows/slack-notifications.yml
    with:
      should_run: true
    secrets: inherit

  increment-patch-version:
    runs-on: ubuntu-latest
    steps:
      - name: echo-patch-version
        run: echo "${{ vars.PATCH_VERSION }}"

  # call-build-workflow:
  #   uses: ./.github/workflows/build.yml
  #   with:
  #     registry: "ghcr.io"
  #     image-name-api: "backend-api"
  #     version: "v1.0.1"
  #   secrets: inherit
