name: nightly-build
on:
  schedule:
    # hourly.
    - cron: "*/15 * * * *"

jobs:
  call-check-should-run:
    uses: ./.github/workflows/should_run.yml

  call-release:
    uses: ./.github/workflows/release.yml
    needs: call-check-should-run
    if: ${{ needs.call-check-should-run.outputs.should_run }} == ''

  # echo_should_run:
  #   runs-on: ubuntu-latest
  #   needs: call-check-should-run
  #   steps:
  #     - name: print output
  #       env:
  #         SHOULD_RUN: ${{ needs.call-check-should-run.outputs.should_run }}
  #       run: echo "$SHOULD_RUN"

  # build_condintional:
  #   runs-on: ubuntu-latest
  #   needs: call-check-should-run
  #   steps:
  #     - name: nightly build
  #       if: ${{ needs.call-check-should-run.outputs.should_run }} == 'true'
  #       run: echo "run nightly build"

  call-notify-slack:
    uses: ./.github/workflows/slack-notifications.yml
    needs: call-release
    with:
      version: ${{ needs.call-release.outputs.version }}
    if: ${{ needs.call-release.outputs.released }} == 'true'
    secrets: inherit

  call-build-workflow:
    needs:
      - call-check-should-run
      - call-release
    uses: ./.github/workflows/build.yml
    if: (${{ needs.call-check-should-run.outputs.should_run }} == 'true' && ${{ needs.call-release.outputs.released }} == 'true')
    with:
      registry: "ghcr.io"
      image-name-api: "backend-api"
      version: ${{ needs.call-release.outputs.version }}
    secrets: inherit
