name: run-workflow-regularly
on:
  schedule: 
  # NY - 3AM Weekdays
    - cron: '0 8 * * 1-5'
  # LA - 3AM Weekdays
    - cron: '0 11 * * 1-5'
jobs: 
  fake-job:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo 'workflow ran!'