name: nightly-build
on:
  schedule:
    # hourly.
    - cron: "30 * * * *"

jobs:
  call-check-should-run:
    uses: ./.github/workflows/should_run.yml
    with:
      foo: "whiz"

  echo_should_run:
    runs-on: ubuntu-latest
    needs: call-check-should-run
    steps:
      - name: print output
        env:
          SHOULD_RUN: ${{ needs.call-check-should-run.outputs.should_run }}
        run: echo "$SHOULD_RUN"

  build_condintional:
    runs-on: ubuntu-latest
    needs: call-check-should-run
    steps:
      - name: nightly build
        if: ${{ needs.call-check-should-run.outputs.should_run }} == true
        run: echo "run nightly build"
